data_path: "./dataset/text"
# ベクトル化手法 -> ['count', tfidf]のどれか
method: "tfidf"
# kernel ->['linear'、 'poly'、 'rbf'、 'sigmoid'、 'precomputed']のどれか
kernel: "rbf"
# model -> [logistic, SVC, RandomForest]のどれか
model: "SVC"